[project]
authors = [{name = "Calixte Henry", email = "131826512+CalHenry@users.noreply.github.com"}]
name = "ai_scrapper_jobmarket"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = [ "crawl4ai>=0.7.1,<0.8", "nest-asyncio>=1.6.0,<2"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
ai_scrapper_jobmarket = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
polars = ">=1.31.0,<2"
